FlaskCrud/model/models.py
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

class FuncCadastrado(db.Model):
    __tablename__='funcionario'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nome = db.Column(db.String(100))
    sobrenome = db.Column(db.String(100))
    funcao = db.Column(db.String(100))

    def __repr__(self):
        return 'func_cadastrado %r' %self.nome
    

FlaskCrud/app.py
from flask import Flask, render_template, request, redirect, url_for
from flask_sqlalchemy import SQLAlchemy
from routes.route import funcionarios
from model.models import db


app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///db.sqlite'


db.init_app(app)
app.register_blueprint(funcionarios)
with app.app_context():
    db.create_all()

app.run(debug=True)

FlaskCrud/controllers/funcController.py
from model.models import FuncCadastrado, db
from flask_sqlalchemy import SQLAlchemy


class ControllerFuncionario:
    @staticmethod
    def create(nome, sobrenome, funcao):
        novo_func = FuncCadastrado(nome=nome, sobrenome=sobrenome, funcao=funcao)
        print(novo_func)
        db.session.add(novo_func)
        db.session.commit()
        return novo_func
    
    @staticmethod
    def read():
        return FuncCadastrado.query.all()
    
    @staticmethod
    def read_id(id):
        return FuncCadastrado.query.get(id)
    
    @staticmethod
    def update(id, nome, sobrenome, funcao):
        func = FuncCadastrado.query.get(id)
        func.nome = nome
        func.sobrenome = sobrenome
        func.funcao = funcao
        db.session.commit()
        return func
    @staticmethod
    def delete(id):
        func = FuncCadastrado.query.get(id)
        db.session.delete(func)
        db.session.commit()

FlaskCrud/routes/route.py
from flask import Flask, render_template, request, redirect, url_for, jsonify, Blueprint
from model.models import FuncCadastrado
from controllers.funcController import ControllerFuncionario

app = Flask(__name__)

funcionarios = Blueprint('funcionarios', __name__)

@funcionarios.route("/", methods=["GET", "POST"])
def main():
    return render_template("funcionarios.html")

@funcionarios.route("/search", methods=["GET"])
def search_func():
    query = request.args.get('q', '')
    if query:
        func = FuncCadastrado.query.filter(FuncCadastrado.nome.like(f'%{query}')).all()
        print('funcionarios')
        return jsonify([func.to_dict() for func in funcionarios])
    return jsonify([])

@funcionarios.route("/cadastro", methods=["POST", "GET"])
def criar_func():
    if request.method == "GET":
        return render_template("form.html")
    data = request.form.to_dict()
    nome = data.get('nome')
    sobrenome = data.get('sobrenome')
    funcao = data.get('funcao')
    if nome and sobrenome and funcao:
        ControllerFuncionario.create(nome, sobrenome, funcao)
        return redirect(url_for('funcionarios.listar_funcionarios'))
    else:
        return jsonify({'erro': 'Todos os campos são obrigatórios'}), 400
    
@funcionarios.route("/funcionarios", methods=["GET"])
def listar_funcionarios():
    funcs = ControllerFuncionario.read()
    return render_template("funcionarios.html", funcs=funcs)


@funcionarios.route("/funcionarios/<int:id>", methods=["GET"])
def delete_func(id):
    ControllerFuncionario.delete(id)
    return redirect(url_for('funcionarios.listar_funcionarios'))

@funcionarios.route("/funcinarios/<int:id>", methods=["POST", "GET"])
def edit_func(id):
    func = ControllerFuncionario.read_id(id)
    if request.method == "GET":
        return render_template("edit.html", func=func)
    data = request.form.to_dict()
    nome = data.get('nome')
    sobrenome = data.get('sobrenome')
    funcao = data.get('funcao')
    ControllerFuncionario.update(id, nome, sobrenome, funcao)
    
    return redirect(url_for('funcionarios.listar_funcionarios'))


FlaskCrud/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Funcionário</title>
    <link rel="stylesheet" href="{{url_for('static', filename='edit.css')}}">
    <link rel="stylesheet" href="../static/edit.css">
</head>
<body>
    <header>
        <h1>Editar Funcionário</h1>
    </header>
    <div class="form-edit">
        <form id="edit-form" action="{{ url_for('funcionarios.edit_func', id=func.id)}}" method="POST">
            <label for="nome">Novo Nome:</label>
            <input type="text" id="nome" name="nome" value="{{ func.nome }}" required><br>

            <label for="sobrenome">Novo Sobrenome:</label>
            <input type="text" id="sobrenome" name="sobrenome" value="{{ func.sobrenome }}" required><br>

            <label for="funcao">Nova Função:</label>
            <input type="text" id="funcao" name="funcao" value="{{ func.funcao }}" required><br>

            <button type="submit">Salvar Alterações</button>
        </form>
    </div>
    
</body>
</html>

FlaskCrud/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Funcionários</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='form.css')}}">
</head>
<body>
    <header>
        <h1>Cadastro de Funcionários</h1>
    </header>
    <form id="cadastro-form" action="{{ url_for('funcionarios.criar_func')}}" method="POST">
        <label for="nome">Nome:</label>
        <input type="text" id="nome" name="nome" required><br>

        <label for="sobrenome">Sobrenome:</label>
        <input type="text" id="sobrenome" name="sobrenome" required><br>

        <label for="funcao">Função:</label>
        <input type="text" id="funcao" name="funcao" required><br>

        <button type="submit">Cadastrar</button>
    </form>
</body>
</html>

FlaskCrud/templates/funcionarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Funcionários</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
</head>
<body>
    <header>
        <h1>Funcionários</h1>
    </header>
    <table>
        <tr>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>Função</th>
        </tr>
        {% for func in funcs %}
        <tr>
            <td>{{ func.nome }}</td>
            <td>{{ func.sobrenome }}</td>
            <td>{{ func.funcao }}</td>
            <td class="btns">
                <a href="{{url_for('funcionarios.delete_func', id=func.id)}}"><button class="delete">Deletar</button></a>
                <a href="{{url_for('funcionarios.edit_func', id=func.id)}}"><button class="edit">Editar</button></a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <div class="btn-cadastrar">
        <a href="{{url_for('funcionarios.criar_func')}}"><button>Cadastrar Funcionario</button></a>
    </div>

</body>
</html>